# Generated by Django 3.0 on 2019-12-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191211_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='+380', max_length=50, verbose_name='Телефон'),
        ),
    ]
