# Generated by Django 3.0.2 on 2020-03-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200304_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='price_usd',
        ),
    ]
