# Generated by Django 3.0.2 on 2020-03-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200305_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(db_index=True, default='+380', max_length=50, verbose_name='Телефон'),
        ),
    ]
