# Generated by Django 3.0.2 on 2020-03-28 01:25

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200328_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kurs_d',
            field=models.ForeignKey(default=shop.models.get_foo, on_delete=django.db.models.deletion.CASCADE, related_name='kurs', to='shop.Kurs', verbose_name='Курс'),
        ),
    ]
