# Generated by Django 3.0.2 on 2020-03-28 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200328_0325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kurs',
            new_name='Kurs_d',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kurs',
        ),
    ]
