# Generated by Django 3.0.2 on 2020-03-28 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200328_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kurs_d',
        ),
    ]
