# Generated by Django 3.0.2 on 2020-03-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_kurs_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kurs',
            field=models.DecimalField(decimal_places=2, default=21.34, max_digits=20, verbose_name='Курс долару'),
        ),
    ]
