# Generated by Django 3.0.2 on 2020-03-28 01:33

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kurs',
            field=models.ForeignKey(default=shop.models.get_foo, on_delete=django.db.models.deletion.CASCADE, related_name='kurs', to='shop.Kurs_d', verbose_name='Курс'),
        ),
    ]
