# Generated by Django 3.0.2 on 2020-03-28 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_kurs_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs_d',
            name='parent',
        ),
    ]
