# Generated by Django 3.0.2 on 2020-03-26 00:27

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200326_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemprice',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemprice',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemprice',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pri',
            field=mptt.fields.TreeForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.ItemPrice', verbose_name='Прайс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='item',
            field=mptt.fields.TreeForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ItemPrice', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='value',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Значение'),
        ),
    ]
