# Generated by Django 3.0.2 on 2020-03-26 00:39

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200326_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemprice',
            old_name='item',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='product',
            name='pri',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ItemPrice', verbose_name='Прайс'),
        ),
    ]
