# Generated by Django 3.0.2 on 2020-03-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200328_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kurs_d',
        ),
        migrations.AddField(
            model_name='product',
            name='kurs_d',
            field=models.ManyToManyField(default=1, related_name='kurs_d', to='shop.Kurs_d', verbose_name='Курс'),
        ),
    ]
