# Generated by Django 3.0.2 on 2020-03-26 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200326_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemprice',
            old_name='parent',
            new_name='item',
        ),
    ]
