# Generated by Django 3.0.2 on 2020-03-26 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200326_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pri',
        ),
        migrations.DeleteModel(
            name='ItemPrice',
        ),
    ]
