# Generated by Django 3.0.2 on 2020-03-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200326_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('zn', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курс',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurs', to='shop.Kurs'),
        ),
    ]
