# Generated by Django 3.0.2 on 2020-03-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200327_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kurs',
        ),
    ]
