# Generated by Django 3.0.2 on 2020-03-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_kurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
