# Generated by Django 3.0.2 on 2020-03-28 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_kurs_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Kurs'),
        ),
    ]
