# Generated by Django 3.0.2 on 2020-03-28 00:56

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_kurs_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kurs_d',
            field=mptt.fields.TreeForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Kurs', verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
