# Generated by Django 3.0.2 on 2020-03-28 00:59

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_kurs_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='level',
            field=models.PositiveIntegerField(default=12, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurs',
            name='lft',
            field=models.PositiveIntegerField(default=12, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurs',
            name='rght',
            field=models.PositiveIntegerField(default=12, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurs',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=12, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kurs',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Kurs'),
        ),
    ]
