# Generated by Django 3.0.2 on 2020-03-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200328_0410'),
        ('shop', '0023_auto_20200328_0259'),
        ('shop', '0010_auto_20200328_0338'),
    ]

    operations = [
    ]
