# Generated by Django 3.0.2 on 2020-03-28 02:40

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_merge_20200328_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs_d',
            name='level',
        ),
        migrations.RemoveField(
            model_name='kurs_d',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='kurs_d',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='kurs_d',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kurs_d',
        ),
        migrations.AddField(
            model_name='product',
            name='kurs_d',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kurs_d', to='shop.Kurs_d', verbose_name='Курс'),
        ),
    ]
