# Generated by Django 3.0.2 on 2020-03-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_product_kurs_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kurs_d',
        ),
    ]
