# Generated by Django 3.0.2 on 2020-03-28 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_remove_product_kurs_d'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kurs_d',
        ),
    ]
