# Generated by Django 3.0.2 on 2020-03-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_delete_kurs_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dollar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('num', models.IntegerField(max_length=20)),
            ],
        ),
    ]
