# Generated by Django 3.0.2 on 2020-03-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_dollar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollar',
            name='num',
            field=models.IntegerField(),
        ),
    ]
