# Generated by Django 3.0.2 on 2020-03-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20200328_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AlterField(
            model_name='dollar',
            name='num',
            field=models.IntegerField(verbose_name='Курс валют'),
        ),
    ]
