# Generated by Django 3.0.2 on 2020-03-28 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_product_dollar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dollar',
        ),
    ]
