# Generated by Django 3.0.2 on 2020-04-01 17:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20200328_0534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dollar',
            options={'verbose_name': 'Курс доллару', 'verbose_name_plural': 'Курс доллару'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='kurs',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='abouttext',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name='Про магазин ( Текст )'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='contacts',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, verbose_name='Контакти ( Текст )'),
        ),
    ]
